name: EAS Build
on:
  workflow_dispatch:
    inputs:
      profile:
        description: "Build profile"
        required: true
        default: "production"
        type: choice
        options:
          - development
          - development-device
          - preview
          - production
      baseUrl:
        description: "Base URL for backend (e.g., https://little-world.com)"
        required: true
        default: "https://little-world.com"
      frontendCommitRef:
        description: "Fronted commit ref"
        required: true
        default: "main"

jobs:
  build-ios:
    name: Install and build
    runs-on: ubuntu-builds-small
    steps:
      - name: environment
        run: |
          if [[ "${{ inputs.profile }}" == "preview" ]]; then
            echo "STAGING=true" >> $GITHUB_OUTPUT
            echo "PRODUCTION=false" >> $GITHUB_OUTPUT
          elif [[ "${{ inputs.profile }}" == "production" ]]; then
            echo "PRODUCTION=true" >> $GITHUB_OUTPUT
            echo "STAGING=false" >> $GITHUB_OUTPUT
          fi
      - name: Checkout little-world-native
        uses: actions/checkout@v4
        with:
          path: little-world-native
      - name: Checkout little-world-frontend (sibling)
        uses: actions/checkout@v4
        with:
          repository: a-little-world/little-world-frontend
          ref: ${{ inputs.frontendCommitRef }}
          path: little-world-frontend
          token: ${{ secrets.BOT_PAT }}
      - name: Install pnpm
        run: npm install -g pnpm@latest-10
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: |
          cd little-world-frontend
          npm ci
          cd ../little-world-native
          export SETUP_HOST_DOMAIN=true
          export HTTP_SCHEME="https"
          export HOST_DOMAIN=$(echo "${{ inputs.baseUrl }}" | sed 's|^https\?://||')
          export USE_WSS_WEBSOCKET=true
          ./_scripts/pack_and_update.sh
      - name: Build on EAS
        env:
          IS_CI_BUILD: true
        run: |
          cd little-world-native
          mv eas.ci.json eas.json
          if [[ "${{ steps.environment.PRODUCTION }}" == "true" ]]; then
            mv ./environments/env.prod.ts ./environments/env.ts
          elif [[ "${{ steps.environment.STAGING }}" == "true" ]]; then
            mv ./environments/env.staging.ts ./environments/env.ts
          fi
          eas build --platform ios --profile ${{ inputs.profile }}  --non-interactive --no-wait
